### ISSUE TITLE
SSL warning when visiting Demo site

### ISSUE THREAD

**Issue by foster-hangdaan** [Hexagon/lumocs#2]
I am getting an SSL certificate warning message when vising the [demo site](https://lumocs.56k.guru/):

![image](https://github.com/Hexagon/lumocs/assets/156146315/2a44943e-0fd0-49ae-8b62-729c28c79aac)

It seems that the certificate's domain - `56k.guru` - is not valid for `lumocs.56k.guru`.

**Comment by Hexagon** [comment]
Thanks for the heads up, fixed now :+1:
